---
apiVersion: v1
kind: Service
metadata:
  name: mongohost
  labels:
    app: project
    component: mongohost
spec:
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: project
    component: mongohost
