stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  services: 
    - name: docker:latest
  script:
    - docker ps
    - docker build -t vitaliymikhailoff/project_ui:2.0 ui/
    - docker build -t vitaliymikhailoff/project_crawler:2.0 crawler/

test_unit_job:
  stage: test
  services: 
    - name: docker:latest
  script:
    - docker compose up -d
    - sleep 20
    - docker ps

deploy_job:
  stage: deploy
  script:
    - echo $CI_JOB_ID



