stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - docker build -t vitaliymikhailoff/project_ui:$CI_JOB_ID ui/
    - docker build -t vitaliymikhailoff/project_crawler:$CI_JOB_ID crawler/
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - docker push vitaliymikhailoff/project_ui:$CI_JOB_ID
    - docker push vitaliymikhailoff/project_crawler:$CI_JOB_ID

test_unit_job:
  stage: test
  script:
    - docker compose up -d
    - sleep 20
    - docker ps

deploy_job:
  stage: deploy
  script:
    - echo $CI_JOB_ID



