---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler
  labels:
    app: project
    component: crawler
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: project
      component: crawler
  template:
    metadata:
      name: crawler
      labels:
        app: project
        component: crawler
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: crawler
          ports:
          - containerPort: {{ .Values.service.internalPort }}
            name: crawler
            protocol: TCP
