---
apiVersion: v1
kind: Service
metadata:
  name: crawler
  labels:
    app: project
    component: crawler
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: project
    component: crawler
