---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: project
    component: ui
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: project
      component: ui
  template:
    metadata:
      name: ui
      labels:
        app: project
        component: ui
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: ui
          ports:
          - containerPort: {{ .Values.service.internalPort }}
            name: ui
            protocol: TCP
