---
dependencies:
  - name: ui
    version: "1.0.0"
    repository: "file://../ui"

  - name: crawler
    version: "1.0.0"
    repository: "file://../crawler"

  - name: rabbithost
    version: "1.0.0"
    repository: "file://../rabbitmq"

  - name: mongohost
    version: "1.0.0"
    repository: "file://../mongo"
